# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: [github-actions, master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup ssh keys
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/id_rsa
          cat <<EOT > ~/.ssh/id_rsa
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOT
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add

      - name: Deploy site
        run: |
          npm install
          npm run build
          rsync -avz ./public ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}://home/neuroapex/neuroapex.io
